//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFul_1.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_story
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_story()
        {
            this.tbl_chapter = new HashSet<tbl_chapter>();
            this.tbl_story_comment = new HashSet<tbl_story_comment>();
            this.tbl_story_follow = new HashSet<tbl_story_follow>();
            this.tbl_story_like = new HashSet<tbl_story_like>();
        }
    
        public int C_id { get; set; }
        public string C_title { get; set; }
        public Nullable<int> C_chapter_number { get; set; }
        public string C_introduction { get; set; }
        public string C_image { get; set; }
        public Nullable<int> C_like_number { get; set; }
        public Nullable<int> C_follow_number { get; set; }
        public Nullable<decimal> C_view_number { get; set; }
        public Nullable<int> C_author_id { get; set; }
        public Nullable<int> C_status_id { get; set; }
        public Nullable<int> C_category_id { get; set; }
        public Nullable<int> C_story_type_id { get; set; }
        public Nullable<int> C_schedule_id { get; set; }
    
        public virtual tbl_author tbl_author { get; set; }
        public virtual tbl_category tbl_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chapter> tbl_chapter { get; set; }
        public virtual tbl_status tbl_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_story_comment> tbl_story_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_story_follow> tbl_story_follow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_story_like> tbl_story_like { get; set; }
        public virtual tbl_story_schedule tbl_story_schedule { get; set; }
        public virtual tbl_story_type tbl_story_type { get; set; }
    }
}
