//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFul_1.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_chapter()
        {
            this.tbl_chapter_image = new HashSet<tbl_chapter_image>();
            this.tbl_chapter_comment = new HashSet<tbl_chapter_comment>();
        }
    
        public int C_id { get; set; }
        public string C_title { get; set; }
        public string C_content { get; set; }
        public Nullable<System.DateTime> C_day_create { get; set; }
        public Nullable<int> C_story_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chapter_image> tbl_chapter_image { get; set; }
        public virtual tbl_story tbl_story { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chapter_comment> tbl_chapter_comment { get; set; }
    }
}
