//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFul_1.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public long C_id { get; set; }
        public string C_name { get; set; }
        public string C_image { get; set; }
        public Nullable<int> C_score { get; set; }
        public Nullable<int> C_active { get; set; }
    }
}
