//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFul_1.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_story_follow
    {
        public long C_id { get; set; }
        public Nullable<int> C_user_id { get; set; }
        public Nullable<int> C_story_id { get; set; }
        public Nullable<System.DateTime> day_create { get; set; }
        public Nullable<int> C_folow { get; set; }
    
        public virtual tbl_story tbl_story { get; set; }
    }
}
