//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFul_1.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Level_user
    {
        public int C_id { get; set; }
        public string C_level { get; set; }
        public Nullable<int> C_score_start { get; set; }
        public Nullable<int> C_score_end { get; set; }
    }
}
