//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFul_1.Models.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_author> tbl_author { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_chapter> tbl_chapter { get; set; }
        public virtual DbSet<tbl_chapter_comment> tbl_chapter_comment { get; set; }
        public virtual DbSet<tbl_chapter_image> tbl_chapter_image { get; set; }
        public virtual DbSet<tbl_Level_user> tbl_Level_user { get; set; }
        public virtual DbSet<tbl_status> tbl_status { get; set; }
        public virtual DbSet<tbl_story> tbl_story { get; set; }
        public virtual DbSet<tbl_story_comment> tbl_story_comment { get; set; }
        public virtual DbSet<tbl_story_follow> tbl_story_follow { get; set; }
        public virtual DbSet<tbl_story_like> tbl_story_like { get; set; }
        public virtual DbSet<tbl_story_schedule> tbl_story_schedule { get; set; }
        public virtual DbSet<tbl_story_type> tbl_story_type { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
